app:
  description: ${app.name} is a Spring Boot application written by ${username:Unknown}
  name: MyApp
db:
  driver: org.postgresql.Driver
  user: postgres
  password: root
  url: jdbc:postgresql://localhost:5432/postgres

  pool:
    size: 12
    timeout: 10
  properties:
    first: 123
    second: 456
    third: Third
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
image:
  base:
    url: D:/Software/Tools/javaWorkspace/teacher-case/images
test:
  full:
    message: ${db.driver} AHAHA

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl: validate
    open-in-view: false #database queries can/can't be performed during view rendering. when TRUE, then transactions open on view, to disable set FALSE
  #      default_schema: teacher-case
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


logging:
  level:
    root: INFO
    com.eyogo.http.ApplicationRunner: INFO #OFF
  file:
    name: eyo.log
    path: /