app:
  description: ${app.name} is a Spring Boot application written by ${username:Unknown}
  name: MyApp
  image:
    bucket: images
db:
  driver: org.postgresql.Driver
  user: postgres
  password: root
  url: jdbc:postgresql://localhost:5432/postgres

  pool:
    size: 12
    timeout: 10
  properties:
    first: 123
    second: 456
    third: Third
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
image:
  base:
    url: D:/Software/Tools/javaWorkspace/teacher-case/images
test:
  full:
    message: ${db.driver} AHAHA

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_URL:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl: validate
    open-in-view: false #database queries can/can't be performed during view rendering. when TRUE, then transactions open on view, to disable set FALSE
  #      default_schema: teacher-case
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

logging:
  level:
    root: INFO
    com.eyogo.http.ApplicationRunner: INFO #OFF
    org.springframework.security: DEBUG
  file:
    name: eyo.log
    path: /