name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: sudo apt-get update && sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t teacher-case:latest .

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Push Docker image
        run: docker tag teacher-case:latest ${{ secrets.DOCKER_REGISTRY_USER }}/teacher-case:latest && docker push ${{ secrets.DOCKER_REGISTRY_USER }}/teacher-case:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_REGISTRY_USER }}/teacher-case:latest
            docker-compose -f /root/teacher-case/docker-compose.yml up -d
